#defining variables
bucket_name = "yourbucket name"
folder_name = "foldername_in_s3"
region      = "region"
snowflake_username = "your_snowflake_username"
snowflake_password = "your_snowflake_password"
snowflake_account  = "your_snowflake_account"
snowflake_role     = "role"
snowflake_region   = "region"
warehouse_name     = "the name of warehouse to create"
warehouse_size     = "size of warehouse"
